using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;

namespace ClevoRGB
{
    public enum Key : byte
    {
        ESCAPE,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        PRINT_SCREEN,
        INSERT,
        DELETE,
        HOME,
        END,
        PAGE_UP,
        PAGE_DOWN,

        TILDE,
        ONE,
        TWO,
        THREE,
        FOUR,
        FIVE,
        SIX,
        SEVEN,
        EIGHT,
        NINE,
        ZERO,
        MINUS,
        EQUALS,
        BACKSPACE,
        NUMLOCK,
        NUMPAD_DIVIDE,
        NUMPAD_MULTIPLY,
        NUMPAD_MINUS,

        TAB,
        Q,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P,
        OPEN_BRACKET,
        CLOSE_BRACKET,
        ENTER,
        NUMPAD_SEVEN,
        NUMPAD_EIGHT,
        NUMPAD_NINE,
        NUMPAD_PLUS,

        CAPS_LOCK,
        A,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L,
        SEMICOLON,
        APOSTROPHE,
        HASHTAG,
        NUMPAD_FOUR,
        NUMPAD_FIVE,
        NUMPAD_SIX,

        LEFT_SHIFT,
        BACKSLASH_UK,
        Z,
        X,
        C,
        V,
        B,
        N,
        M,
        COMMA,
        PERIOD,
        FORWARD_SLASH,
        RIGHT_SHIFT,
        UP_ARROW,
        NUMPAD_ONE,
        NUMPAD_TWO,
        NUMPAD_THREE,
        NUMPAD_ENTER,

        LEFT_CONTROL,
        FN_Key,
        LEFT_WINDOWS,
        LEFT_ALT,
        SPACE,
        RIGHT_ALT,
        MENU,
        RIGHT_CONTROL,
        ARROW_LEFT,
        DOWN_ARROW,
        RIGHT_ARROW,
        NUMPAD_0,
        NUMPAD_PERIOD,

        BACKSLASH
    }

    public static class Layouts
    {
        public static readonly Dictionary<Key, int[]> ISO15 = new Dictionary<Key, int[]>
        {
            //0
            [Key.ESCAPE] = new int[] { 0 },
            [Key.F1] = new int[] { 3 },
            [Key.F2] = new int[] { 6 },
            [Key.F3] = new int[] { 9 },
            [Key.F4] = new int[] { 12 },
            [Key.F5] = new int[] { 16 },
            [Key.F6] = new int[] { 19 },
            [Key.F7] = new int[] { 22 },
            [Key.F8] = new int[] { 25 },
            [Key.F9] = new int[] { 28 },
            [Key.F10] = new int[] { 32 },
            [Key.F11] = new int[] { 35 },
            [Key.F12] = new int[] { 38 },
            [Key.PRINT_SCREEN] = new int[] { 41 },
            [Key.INSERT] = new int[] { 44 },
            [Key.DELETE] = new int[] { 48 },
            [Key.HOME] = new int[] { 51 },
            [Key.END] = new int[] { 54 },
            [Key.PAGE_UP] = new int[] { 57 },
            [Key.PAGE_DOWN] = new int[] { 60 },

            //1
            [Key.TILDE] = new int[] { 64 },
            [Key.ONE] = new int[] { 67 },
            [Key.TWO] = new int[] { 70 },
            [Key.THREE] = new int[] { 73 },
            [Key.FOUR] = new int[] { 76 },
            [Key.FIVE] = new int[] { 80 },
            [Key.SIX] = new int[] { 83 },
            [Key.SEVEN] = new int[] { 86 },
            [Key.EIGHT] = new int[] { 89 },
            [Key.NINE] = new int[] { 92 },
            [Key.ZERO] = new int[] { 96 },
            [Key.MINUS] = new int[] { 99 },
            [Key.EQUALS] = new int[] { 105 },
            [Key.BACKSPACE] = new int[] { 108, 112 },
            [Key.NUMLOCK] = new int[] { 115 },
            [Key.NUMPAD_DIVIDE] = new int[] { 118 },
            [Key.NUMPAD_MULTIPLY] = new int[] { 121 },
            [Key.NUMPAD_MINUS] = new int[] { 124 },

            //2
            [Key.TAB] = new int[] { 128, 131 },
            [Key.Q] = new int[] { 134 },
            [Key.W] = new int[] { 137 },
            [Key.E] = new int[] { 140 },
            [Key.R] = new int[] { 144 },
            [Key.T] = new int[] { 147 },
            [Key.Y] = new int[] { 150 },
            [Key.U] = new int[] { 153 },
            [Key.I] = new int[] { 156 },
            [Key.O] = new int[] { 160 },
            [Key.P] = new int[] { 163 },
            [Key.OPEN_BRACKET] = new int[] { 166 },
            [Key.CLOSE_BRACKET] = new int[] { 169 },
            [Key.ENTER] = new int[] { 172, 240 },
            //176 blank
            [Key.NUMPAD_SEVEN] = new int[] { 179 },
            [Key.NUMPAD_EIGHT] = new int[] { 182 },
            [Key.NUMPAD_NINE] = new int[] { 185 },
            [Key.NUMPAD_PLUS] = new int[] { 188, 252 },

            //3
            [Key.CAPS_LOCK] = new int[] { 192, 195 },
            [Key.A] = new int[] { 198 },
            [Key.S] = new int[] { 201 },
            [Key.D] = new int[] { 204 },
            [Key.F] = new int[] { 208 },
            [Key.G] = new int[] { 211 },
            [Key.H] = new int[] { 214 },
            [Key.J] = new int[] { 217 },
            [Key.K] = new int[] { 220 },
            [Key.L] = new int[] { 224 },
            [Key.SEMICOLON] = new int[] { 227 },
            [Key.APOSTROPHE] = new int[] { 230 },
            //233 blank definitely
            [Key.HASHTAG] = new int[] { 236 },
            //240 enter bottom
            [Key.NUMPAD_FOUR] = new int[] { 243 },
            [Key.NUMPAD_FIVE] = new int[] { 246 },
            [Key.NUMPAD_SIX] = new int[] { 249 },
            //252 numpad plus bottom

            //4
            [Key.LEFT_SHIFT] = new int[] { 256 },
            //259
            [Key.BACKSLASH_UK] = new int[] { 262 },
            [Key.Z] = new int[] { 265 },
            [Key.X] = new int[] { 268 },
            [Key.C] = new int[] { 272 },
            [Key.V] = new int[] { 275 },
            [Key.B] = new int[] { 278 },
            [Key.N] = new int[] { 281 },
            [Key.M] = new int[] { 284 },
            [Key.COMMA] = new int[] { 288 },
            [Key.PERIOD] = new int[] { 291 },
            [Key.FORWARD_SLASH] = new int[] { 294 },
            [Key.RIGHT_SHIFT] = new int[] { 297, 300 },
            [Key.UP_ARROW] = new int[] { 304 },
            [Key.NUMPAD_ONE] = new int[] { 307 },
            [Key.NUMPAD_TWO] = new int[] { 310 },
            [Key.NUMPAD_THREE] = new int[] { 313 },
            [Key.NUMPAD_ENTER] = new int[] { 316, 380 },

            //5
            [Key.LEFT_CONTROL] = new int[] { 320, 323 },
            [Key.FN_Key] = new int[] { 326 },
            [Key.LEFT_WINDOWS] = new int[] { 329 },
            [Key.LEFT_ALT] = new int[] { 332 },
            [Key.SPACE] = new int[] { 336, 339, 342, 345, 348 },
            [Key.RIGHT_ALT] = new int[] { 352 },
            [Key.MENU] = new int[] { 355 },
            [Key.RIGHT_CONTROL] = new int[] { 358, 361 },
            [Key.ARROW_LEFT] = new int[] { 364 },
            [Key.DOWN_ARROW] = new int[] { 368 },
            [Key.RIGHT_ARROW] = new int[] { 371 },
            [Key.NUMPAD_0] = new int[] { 374 },
            [Key.NUMPAD_PERIOD] = new int[] { 377 },
            //num enter^
        };
    }
}
